import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

import { VscBeaker, VscBook, VscHome } from "react-icons/vsc";
import Link from "next/link";
import { SiOpenai } from "react-icons/si";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} relative flex min-h-screen flex-col`}>
        <nav className="sticky top-0 z-10 h-12 border-b-1 border-slate-300 bg-slate-100 px-2">
          <ol
            className="container mx-auto flex h-full max-w-6xl flex-row items-center"
            role="list"
          >
            <li className="h-full px-3">
              <Link
                href="/"
                className="flex h-full flex-row items-center gap-3"
              >
                <VscHome className="h-5 w-5" />
                <span>Home</span>
              </Link>
            </li>
            <li className="h-full px-3">
              <Link
                href="/b"
                className="flex h-full flex-row items-center gap-3"
              >
                <VscBook className="h-5 w-5" />
                <span className="hidden sm:inline">Blog</span>
              </Link>
            </li>
            <li className="group relative h-full px-3">
              <a className="flex h-full cursor-pointer flex-row items-center gap-3">
                <VscBeaker className="h-5 w-5" />
                <span className="hidden sm:inline">Experiments</span>
              </a>
              <ol className="absolute right-0 top-full hidden w-max flex-col rounded-b-md border-1 border-slate-300 bg-white group-hover:flex group-focus:flex group-active:flex sm:left-0 sm:right-auto">
                <li>
                  <Link
                    href="/x/lisa-chatgpt"
                    className="flex-wo flex items-center gap-2 px-3 py-3"
                  >
                    <SiOpenai className="h-5 w-5" />
                    LISA ChatGPT
                  </Link>
                </li>
              </ol>
            </li>
          </ol>
        </nav>
        <div className="z-0 flex-1 bg-white">{children}</div>
        <footer className="bg-slate-10 flex flex-row items-center justify-center border-t-1 border-slate-300 bg-slate-100 py-2 text-sm">
          © Elie Rotenberg
        </footer>
      </body>
    </html>
  );
}
