import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

import { VscBeaker, VscBook, VscHome } from "react-icons/vsc";
import Link from "next/link";

const font = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} relative flex min-h-screen flex-col`}>
        <nav className="sticky top-0 z-10 bg-slate-100 px-2 py-4">
          <ol className="container mx-auto flex max-w-3xl flex-row gap-4">
            <li className="flex flex-row items-center">
              <Link href="/" className="flex flex-row items-center gap-1">
                <VscHome className="h-5 w-5" />
                <span>Home</span>
              </Link>
            </li>
            <li className="flex flex-row items-center">
              <Link href="/" className="flex flex-row items-center gap-1">
                <VscBook className="h-5 w-5" />
                <span className="hidden sm:inline">Blog</span>
              </Link>
            </li>
            <li className="flex flex-row items-center">
              <Link href="/" className="flex flex-row items-center gap-1">
                <VscBeaker className="h-5 w-5" />
                <span className="hidden sm:inline">Experiments</span>
              </Link>
            </li>
          </ol>
        </nav>
        <div className="z-0 flex-1 bg-slate-50">{children}</div>
        <footer className="bg-slate-10 flex flex-row items-center justify-center px-2 py-2 text-sm">
          © Elie Rotenberg
        </footer>
      </body>
    </html>
  );
}
