import { dirname, join, relative } from "path";
import { promises } from "fs";
import { fileURLToPath } from "url";

import { globby } from "globby";

// eslint-disable-next-line @typescript-eslint/naming-convention
const __dirname = dirname(fileURLToPath(import.meta.url));

const main = async (): Promise<void> => {
  const postsRoot = join(__dirname, `..`, `src`, `posts`);
  const files = await globby(join(postsRoot, `**`, `*.mdx`));
  const loaders: string[] = [];

  for (const file of files) {
    const relativePath = relative(postsRoot, file);
    loaders.push(`{
      key: ${JSON.stringify(relativePath)},
      loadData: (): Promise<unknown> => import("./${relativePath}").then(module => module.data),
      Mdx: dynamic(() => import("./${relativePath}")),
    }`);
  }

  const code = `
    /******
     * This file is generated by scripts/parse-posts
     * DO NOT EDIT MANUALLY !
     *****/
    import dynamic from "next/dynamic";
    
    export const blogPostsLoaders = [${loaders.join(`,\n`)}]
  `;
  await promises.writeFile(join(postsRoot, `index.ts`), code, {
    encoding: `utf8`,
  });
};

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
