/******
 * This file is generated by scripts/parse-posts
 * DO NOT EDIT MANUALLY !
 *****/
import dynamic from "next/dynamic";

export const blogPostsLoaders = [
  {
    key: `environnement-numerique-ifea-reconfinement.mdx`,
    loadData: (): Promise<unknown> =>
      import(`./environnement-numerique-ifea-reconfinement.mdx`).then(
        (module) => module.data,
      ),
    Mdx: dynamic(
      () => import(`./environnement-numerique-ifea-reconfinement.mdx`),
    ),
  },
  {
    key: `modern-programming-glossary.mdx`,
    loadData: (): Promise<unknown> =>
      import(`./modern-programming-glossary.mdx`).then((module) => module.data),
    Mdx: dynamic(() => import(`./modern-programming-glossary.mdx`)),
  },
];
